"""Retrieval utilities for admission RAG knowledge bases."""

from .embedding import (
    DeterministicFakeEmbeddingProvider,
    EmbeddingError,
    EmbeddingIdentity,
    EmbeddingInputError,
    EmbeddingOutputError,
    EmbeddingProvider,
    EmbeddingProviderError,
    embed_documents_checked,
    embed_query_checked,
    validate_document_embeddings,
    validate_query_embedding,
)
from .embedding_text import EMBEDDING_TEXT_VERSION, build_embedding_text
from .index_freshness import (
    FRESHNESS_CHECKED_FIELDS,
    CurrentKbInputError,
    IndexFreshnessError,
    IndexFreshnessReport,
    StaleIndexError,
    check_index_freshness,
)
from .sentence_transformer import (
    SentenceTransformerConfig,
    SentenceTransformerEmbeddingProvider,
)
from .local_index import (
    INDEX_BUILDER_VERSION,
    IndexArtifactError,
    IndexBuildError,
    IndexLoadError,
    LocalVectorIndex,
    build_local_index,
    load_local_index,
)
from .vector_search import (
    ProviderIdentityMismatchError,
    QueryVectorError,
    SearchInputError,
    VectorSearchError,
    VectorSearchHit,
    VectorSearchResult,
    search_local_index,
    search_loaded_index,
    validate_search_inputs,
)

__all__ = [
    "DeterministicFakeEmbeddingProvider",
    "EmbeddingError",
    "EmbeddingIdentity",
    "EmbeddingInputError",
    "EmbeddingOutputError",
    "EmbeddingProvider",
    "EmbeddingProviderError",
    "EMBEDDING_TEXT_VERSION",
    "FRESHNESS_CHECKED_FIELDS",
    "INDEX_BUILDER_VERSION",
    "IndexArtifactError",
    "IndexBuildError",
    "IndexLoadError",
    "IndexFreshnessError",
    "IndexFreshnessReport",
    "CurrentKbInputError",
    "LocalVectorIndex",
    "ProviderIdentityMismatchError",
    "QueryVectorError",
    "SearchInputError",
    "SentenceTransformerConfig",
    "SentenceTransformerEmbeddingProvider",
    "StaleIndexError",
    "VectorSearchError",
    "VectorSearchHit",
    "VectorSearchResult",
    "build_embedding_text",
    "build_local_index",
    "check_index_freshness",
    "embed_documents_checked",
    "embed_query_checked",
    "load_local_index",
    "search_local_index",
    "search_loaded_index",
    "validate_search_inputs",
    "validate_document_embeddings",
    "validate_query_embedding",
]
