"""Pydantic and dataclass schemas for admission RAG knowledge bases."""

from .corpus_manifest import (
    CORPUS_MANIFEST_SCHEMA_VERSION,
    SUPPORTED_CORPUS_MANIFEST_SCHEMA_VERSIONS,
    CorpusDocumentEntry,
    CorpusIndexManifest,
    CorpusManifest,
    CorpusManifestError,
    canonical_corpus_manifest_bytes,
    load_corpus_manifest,
    load_corpus_manifest_bytes,
)

from .document_identity import (
    DOCUMENT_IDENTITY_SCHEMA_VERSION,
    SUPPORTED_DOCUMENT_IDENTITY_SCHEMA_VERSIONS,
    DegreeLevel,
    DocumentIdentity,
    DocumentIdentityError,
    IntakeTerm,
    canonical_document_identity_bytes,
    load_document_identity,
    load_document_identity_bytes,
)
from .document_kb import (
    DocumentKnowledgeBase,
    DocumentKnowledgeBaseError,
    KnowledgeManifest,
    LegacyDocumentKnowledgeBaseV05,
    LegacyKnowledgeManifestV05,
    canonical_document_kb_bytes,
    load_document_kb,
    load_document_kb_bytes,
    migrate_document_kb_v05,
    migrate_document_kb_v05_bytes,
)

from .evidence_pack import (
    EVIDENCE_PACK_SCHEMA_VERSION,
    SUPPORTED_EVIDENCE_PACK_SCHEMA_VERSIONS,
    AttachedReferenceEvidence,
    EvidenceCounts,
    EvidenceMetadataFilter,
    EvidencePack,
    EvidencePackError,
    EvidenceRequest,
    EvidenceRuntime,
    EvidenceScopePreference,
    IncomingRelation,
    PrimaryEvidence,
    ReferenceWarning,
    ResolvedReferenceRelation,
    canonical_evidence_pack_bytes,
    load_evidence_pack,
    load_evidence_pack_bytes,
)

__all__ = [
    "CORPUS_MANIFEST_SCHEMA_VERSION",
    "SUPPORTED_CORPUS_MANIFEST_SCHEMA_VERSIONS",
    "CorpusDocumentEntry",
    "CorpusIndexManifest",
    "CorpusManifest",
    "CorpusManifestError",
    "canonical_corpus_manifest_bytes",
    "load_corpus_manifest",
    "load_corpus_manifest_bytes",
    "DOCUMENT_IDENTITY_SCHEMA_VERSION",
    "SUPPORTED_DOCUMENT_IDENTITY_SCHEMA_VERSIONS",
    "DegreeLevel",
    "DocumentIdentity",
    "DocumentIdentityError",
    "IntakeTerm",
    "canonical_document_identity_bytes",
    "load_document_identity",
    "load_document_identity_bytes",
    "DocumentKnowledgeBase",
    "DocumentKnowledgeBaseError",
    "KnowledgeManifest",
    "LegacyDocumentKnowledgeBaseV05",
    "LegacyKnowledgeManifestV05",
    "canonical_document_kb_bytes",
    "load_document_kb",
    "load_document_kb_bytes",
    "migrate_document_kb_v05",
    "migrate_document_kb_v05_bytes",
    "EVIDENCE_PACK_SCHEMA_VERSION",
    "SUPPORTED_EVIDENCE_PACK_SCHEMA_VERSIONS",
    "AttachedReferenceEvidence",
    "EvidenceCounts",
    "EvidenceMetadataFilter",
    "EvidencePack",
    "EvidencePackError",
    "EvidenceRequest",
    "EvidenceRuntime",
    "EvidenceScopePreference",
    "IncomingRelation",
    "PrimaryEvidence",
    "ReferenceWarning",
    "ResolvedReferenceRelation",
    "canonical_evidence_pack_bytes",
    "load_evidence_pack",
    "load_evidence_pack_bytes",
]
